print("Cálculo del área de un triángulo ")
...
... base = float(input("10: "))
... altura = float(input("5: "))
...
... area = (base * altura) / 2
...
... print(f"El área del triángulo es: {area} ")
